# Generated by Django 4.0.5 on 2022-07-09 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Gallery',
        ),
    ]
