# Generated by Django 4.0.5 on 2022-07-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_rename_image_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_text', models.CharField(max_length=5000)),
            ],
        ),
    ]
