# Generated by Django 4.0.5 on 2022-07-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
